# Generated by Django 6.0 on 2026-01-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("rule_number", models.IntegerField(editable=False)),
                (
                    "week",
                    models.CharField(
                        choices=[
                            ("اول", "اول"),
                            ("دوم", "دوم"),
                            ("سوم", "سوم"),
                            ("چهارم", "چهارم"),
                            ("فرقی نمی کند", "فرقی نمی کند"),
                        ],
                        default="فرقی نمی کند",
                        max_length=50,
                    ),
                ),
                (
                    "activation_base",
                    models.CharField(
                        choices=[
                            ("همیشه", "همیشه"),
                            ("آخرین خرید", "آخرین خرید"),
                            ("اولین خرید", "اولین خرید"),
                            ("تاریخ خرید بعدی", "تاریخ خرید بعدی"),
                            ("دسته بندی مشتری", "دسته بندی مشتری"),
                            ("یادآوری خرید بعدی", "یادآوری خرید بعدی"),
                        ],
                        default="همیشه",
                        max_length=50,
                    ),
                ),
                (
                    "comparison_type",
                    models.CharField(
                        choices=[
                            ("بزرگتر از", "بزرگتر از"),
                            ("کوچکتر از", "کوچکتر از"),
                            ("برابر با", "برابر با"),
                        ],
                        default="بزرگتر از",
                        max_length=50,
                    ),
                ),
                (
                    "comparison_value",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                            (13, 13),
                            (14, 14),
                            (15, 15),
                            (120, 120),
                            (200, 200),
                            (400, 400),
                        ],
                        default=1,
                    ),
                ),
                (
                    "value_unit",
                    models.CharField(
                        choices=[
                            ("روز", "روز"),
                            ("درصد", "درصد"),
                            ("سفارش", "سفارش"),
                            ("تومان", "تومان"),
                            ("تعداد", "تعداد"),
                        ],
                        default="روز",
                        max_length=50,
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("همه", "همه"),
                            ("ویژه", "ویژه"),
                            ("فعال", "فعال"),
                            ("در خطر ریزش", "در خطر ریزش"),
                            ("از دست رفته", "از دست رفته"),
                        ],
                        default="همه",
                        max_length=50,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("آقایان", "آقایان"),
                            ("بانوان", "بانوان"),
                            ("همه", "همه"),
                        ],
                        default="همه",
                        max_length=10,
                    ),
                ),
                (
                    "skin_type",
                    models.CharField(
                        choices=[
                            ("پوست مختلط", "پوست مختلط"),
                            ("پوست چرب", "پوست چرب"),
                            ("پوست خشک", "پوست خشک"),
                            ("همه", "همه"),
                        ],
                        default="همه",
                        max_length=50,
                    ),
                ),
                (
                    "hair_type",
                    models.CharField(
                        choices=[
                            ("موی مختلط", "موی مختلط"),
                            ("موی چرب", "موی چرب"),
                            ("موی خشک", "موی خشک"),
                            ("همه", "همه"),
                        ],
                        default="همه",
                        max_length=50,
                    ),
                ),
                (
                    "product_source",
                    models.CharField(
                        choices=[
                            ("اولین محصول پرفروش", "اولین محصول پرفروش"),
                            ("دومین محصول پرفروش", "دومین محصول پرفروش"),
                            ("سومین محصول پرفروش", "سومین محصول پرفروش"),
                            (
                                "آخرین خرید + میانگین دوره خرید محصول",
                                "آخرین خرید + میانگین دوره خرید محصول",
                            ),
                            (
                                "پرتکرارترین محصول خریداری شده کاربر",
                                "پرتکرارترین محصول خریداری شده کاربر",
                            ),
                            ("هیچ کدام", "هیچ کدام"),
                        ],
                        default="اولین محصول پرفروش",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "customers_file",
                    models.FileField(
                        blank=True, null=True, upload_to="campaign_customers/"
                    ),
                ),
                ("message_pattern", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_id"], name="core_campai_tenant__ca24ce_idx"
                    )
                ],
            },
        ),
    ]
