# Generated by Django 6.0 on 2026-01-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="priority",
            field=models.CharField(
                choices=[
                    ("خیلی بالا", "خیلی بالا"),
                    ("بالا", "بالا"),
                    ("متوسط", "متوسط"),
                    ("پایین", "پایین"),
                    ("خیلی پایین", "خیلی پایین"),
                ],
                default="خیلی بالا",
                max_length=20,
            ),
        ),
    ]
