# Generated by Django 6.0 on 2026-01-30 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_campaign_priority"),
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="category",
        ),
        migrations.AddField(
            model_name="ticket",
            name="related_campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.campaign",
            ),
        ),
        migrations.DeleteModel(
            name="TicketCategory",
        ),
    ]
