# Generated by Django 6.0 on 2026-01-31 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_remove_ticket_category_ticket_related_campaign_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="related_campaign",
        ),
        migrations.DeleteModel(
            name="TicketAttachment",
        ),
    ]
